### ISSUE TITLE
[issue] small fixes

### ISSUE THREAD

**Issue by krzysztof-kabala** [faja/yake#1]
1) if `showcmd` is set as "false" at the bottom the exit status code is shown, e.g.:

```
[...]

exit status 129
```

Could be removed if `showcmd: false`

2) `PROJECT_BIN` var name or simillar can ba available as real program name, so string on left side of task name, like:
`./yake MY_VAR=1 task ...` => `PROJECT_BIN = ./yake MY_VAR=1`

3) README to update

**Comment by faja** [comment]
1) that's indeed a bug and it's fixed now
2) curently you can define a variable before or after the task name, because of that creating a new variable `PROJECT_BIN` containing everything on the left side of the task name doesn't make much sense. I'm pretty sure you can do some task nesting quite easily with a proper Yakefile.
3) README will be updated

**Comment by faja** [comment]
2) I've changed argument parsing logic and now variables have to be placed before taskname.
Executable name and all variables are available under `BIN` variable, eg:
Yakefile:

```
task3: echo $BIN
```

```
% ./yake_renamved XX=yy test3
>>> echo ./yake_renamved XX=yy
```

hope that's what you wanted:)
3) done

**Comment by faja** [comment]
Are you happy to close this issue?

**Comment by krzysztof-kabala** [comment]
yes, can be closed, works perfectly now! :)
